### ISSUE TITLE
[Bug]: NVMe controller is still broken for Windows 10/11 guests

### ISSUE THREAD

**Issue by birdie-github** [VirtualBox/virtualbox#126]
### Version

trunk/main

### Host OS Type

Windows

### Host OS name + version

N/A

### Host Architecture

x86

### Guest OS Type

Windows

### Guest Architecture

x86

### Guest OS name + version

Any version of Windows 10/Windows 11

### Component

Storage and Virtual Disks

### What happened?

This has been known for years, check

https://www.virtualbox.org/ticket/21777

This is still reproducible in VirtualBox 7.2-RC1.

### How can we reproduce this?

Steps to reproduce:
1. Create a Windows 10/11 guest
2. Add an NVMe controller
3. Remove the disk from the SATA controller and attach it to the NVMe controller.

Results:
Windows fails to detect the NVMe controller and its attached storage devices.

Not attaching any files because it takes 1 minute to reproduce.

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by ArakelYorghanjyan** [comment]
The problem is really relevant and is reproduced even on version 7.2.2

**Comment by birdie-github** [comment]
In case the old bug tracker website goes down:

The following workaround still works:
```
    VBoxManage setextradata <VM name> "VBoxInternal/Devices/nvme/0/Config/MsiXSupported" 0
    VBoxManage setextradata <VM name> "VBoxInternal/Devices/nvme/0/Config/CtrlMemBufSize" 0
```

**Comment by AlexanderEichner** [comment]
Unfortunately changing the defaults to make it work by default is extremely difficult because it would break existing saved states. And because NVMe is not the default for VMs there wasn't any real pressure to try fixing this in a compatible way so far. So far we believe that this is a bug in Microsoft's NVMe driver because it works with other guests.

**Comment by birdie-github** [comment]
There's no way Microsoft will ever fix Windows 8/10 because they are basically unsupported now, so you may as well add these options for new Windows guests until Microsoft bothers to fix this bug (and I'm not sure they ever will) at least in Windows 11. Or maybe the existence of this bug report is enough for those who want to experiment with NVMe drives under Windows.

**Comment by ArakelYorghanjyan** [comment]
Is there an open support request with Microsoft regarding this issue?
Or have we assumed this is a Microsoft issue, while no one at Microsoft knows anything about it?
Is there a reason for Microsoft to fix this issue or to adapt their driver for VirtualBox? Perhaps, from Microsoft's perspective, VirtualBox issues should be resolved by VirtualBox itself?

**Comment by birdie-github** [comment]
@daviburg @jstedfast

David and Jeffrey, sorry for the notification. Could you ask around and see if Microsoft could at least look into this issue with regard to Windows 11? It has been around since Windows 8.

@AlexanderEichner 

Can Oracle escalate this through the Microsoft Windows Hardware Partner channel? I'm an absolute no one and even if I file a report e.g. via the official channels, no one will ever do anything about it.

**Comment by TheFabio** [comment]
# Confirming ongoing Issue with Windows 11 VM on NVMe Storage

I can confirm that this issue persists even after upgrading to NVMe storage. Here are the specifics of my recent experiments:

Current Setup:

- Host Linux Mint 22.1
- VirtuaBox v7.2.4 (VBox)
- Recent Hardware Upgrade: NVMe storage installed.
- Virtual Machines (VMs):
   - VM 1: Windows 10
   - VM 2: Windows 11

Initial Configuration: Both VMs initially retained the VBox SATA controller.

Observations:

- Windows 10 VM:
    - Functions normally
    - Performance is consistent, similar to when it was on the SSD.

- Windows 11 VM:
    - Exhibits significant performance issues.
    - Any Guest IO-intensive operations drastically increase the host's CPU usage.

# Experiments Conducted:
## Experiment 1:

Objective: To apply configurations and commands suggested in the issue to see if it resolves the performance issue.

Steps Taken:

1. Added an NVMe controller to the Windows 11 VM.
2. Removed the disk from the SATA controller and attached it to the NVMe controller.
3. Executed the following commands:
```
VBoxManage setextradata "<VM name>" "VBoxInternal/Devices/nvme/0/Config/MsiXSupported" 0
VBoxManage setextradata "<VM name>" "VBoxInternal/Devices/nvme/0/Config/CtrlMemBufSize" 0
```
Outcome: Despite attempts to configure the VM, the fail to start remains unresolved. Windows 11 VM still encounters the same issue even after letting Windows attempt automatic fixes.
Error Screenshot
<img width="905" height="486" alt="Image" src="https://github.com/user-attachments/assets/39f545fe-d9cf-49f4-922e-8143f4618893" />

## Experiment 2:

Objective: To test if reverting the Windows 11 VM back to SSD storage resolves the performance issue.

Steps Taken:

- Restored the original Windows 11 VM backup to SSD storage.

Outcome: The Windows 11 VM operates normally and efficiently on the SSD storage.

## Conclusion:

For the time being, I will keep my Windows 11 VM on the SSD storage until this issue is reported as resolved by VBox. Notably, other VMs with various operating systems on the same hardware do not experience this issue, suggesting a peculiar bug or feature with Windows 11 that is causing the performance degradation.
