### ISSUE TITLE
[Bug]: VirtualBoxVM.exe - Application Error - The instruction at 0x00007FFFA88C1297 referenced memory at 0x0000000000000000. The memory could not be read.

### ISSUE THREAD

**Issue by TommiPrami** [VirtualBox/virtualbox#207]
### Version

7.2.0

### Host OS Type

Windows

### Host OS name + version

OS Name	Microsoft Windows 11 Pro - Version	10.0.26100 Build 26100

### Host Architecture

x86

### Guest OS Type

Windows

### Guest Architecture

x86

### Guest OS name + version

OS Name	Microsoft Windows 11 Home - Version	10.0.22621 Build 22621

### Component

Unspecified

### What happened?

This happesn some times whn booting Guest.

Noty 100% alkways. WVirtal machine, the guest machine, will ddie instantly after that.

[VBoxLog1.txt](https://github.com/user-attachments/files/22248736/VBoxLog1.txt)
[VBoxLog2.txt](https://github.com/user-attachments/files/22248735/VBoxLog2.txt)
[VBoxLog3.txt](https://github.com/user-attachments/files/22248732/VBoxLog3.txt)
[Hardening.txt](https://github.com/user-attachments/files/22248734/Hardening.txt)
[Log.txt](https://github.com/user-attachments/files/22248733/Log.txt)

### How can we reproduce this?

No idea how you, but happen for me some times, have feweling that this is related to Win11 Guest, but not sure.

### Did you upload *all* of your necessary log files, screenshots, etc.?

- [x] Yes, I've uploaded all pertinent files to this issue.

**Comment by TommiPrami** [comment]
<img width="1325" height="733" alt="Image" src="https://github.com/user-attachments/assets/63ae89af-050d-466e-a5fe-a2ad969a621e" />

**Comment by TommiPrami** [comment]
<img width="478" height="235" alt="Image" src="https://github.com/user-attachments/assets/114d4245-f226-4452-aa51-c99ddefa368c" />

Coworker got propably same error, but address seems differrent...

**Comment by pspot2** [comment]
For me this started happening after upgrading to 7.2.2.

Host OS: Windows 10
Guest OS: Linux (x86_64)

I noticed that this crash is consistent as long as the option `Enable 3D acceleration` remains unticked (my normal setup). After ticking this option, the VM boots fine, but the following messages about kernel `vmwgfx` driver are being constantly written to `dmesg`:

```
Sep 15 00:07:01 vmgentoo kernel: ------------[ cut here ]------------
Sep 15 00:07:01 vmgentoo kernel: Fence vmwgfx:svga:1:1f08a released with pending signals!
Sep 15 00:07:01 vmgentoo kernel: WARNING: CPU: 3 PID: 1575 at drivers/dma-buf/dma-fence.c:538 dma_fence_release+0x8c/0x100
Sep 15 00:07:01 vmgentoo kernel: Modules linked in: fuse vboxsf(O) snd_hda_codec_idt snd_hda_codec_generic snd_hda_intel snd_intel_dspcfg intel_rapl_msr snd_hda_codec intel_rapl_common hi
d_multitouch snd_hwdep snd_hda_core snd_pcm crc32_pclmul crc32c_intel vmwgfx sha512_ssse3 sha256_ssse3 sha1_ssse3 snd_timer drm_ttm_helper aesni_intel snd i2c_piix4 virtio_net ttm crypto_
simd vboxguest(O) i2c_smbus cryptd soundcore efivarfs
Sep 15 00:07:01 vmgentoo kernel: CPU: 3 UID: 1001 PID: 1575 Comm: kwin_wayland Tainted: G        W  O       6.12.41 #1
Sep 15 00:07:01 vmgentoo kernel: Tainted: [W]=WARN, [O]=OOT_MODULE
Sep 15 00:07:01 vmgentoo kernel: Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
Sep 15 00:07:01 vmgentoo kernel: RIP: 0010:dma_fence_release+0x8c/0x100
Sep 15 00:07:01 vmgentoo kernel: Code: 89 ef 49 89 c5 48 8b 43 d0 48 8b 40 08 e8 fc bb 2f 00 4d 89 f8 4c 89 f1 4c 89 ea 48 89 c6 48 c7 c7 10 51 4c b6 e8 64 21 b3 ff <0f> 0b 48 8b 7b c8 e8
 19 b0 2f 00 c7 43 04 dd ff ff ff 49 89 c5 e8
Sep 15 00:07:01 vmgentoo kernel: RSP: 0018:ffffb409806cfeb0 EFLAGS: 00010286
Sep 15 00:07:01 vmgentoo kernel: RAX: 0000000000000000 RBX: ffff993b8ebc48b0 RCX: 0000000000000027
Sep 15 00:07:01 vmgentoo kernel: RDX: ffff993fc08db908 RSI: 0000000000000001 RDI: ffff993fc08db900
Sep 15 00:07:01 vmgentoo kernel: RBP: ffff993b8ebc4878 R08: ffffffffb66c9340 R09: 000000000003d6f8
Sep 15 00:07:01 vmgentoo kernel: R10: 0000000000000003 R11: 21736c616e676973 R12: ffff993b8ebc4888
Sep 15 00:07:01 vmgentoo kernel: R13: ffffffffc0313f38 R14: 0000000000000001 R15: 000000000001f08a
Sep 15 00:07:01 vmgentoo kernel: FS:  00007f3ad83b2980(0000) GS:ffff993fc08c0000(0000) knlGS:0000000000000000
Sep 15 00:07:01 vmgentoo kernel: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Sep 15 00:07:01 vmgentoo kernel: CR2: 00007f3ac4480a50 CR3: 0000000109166004 CR4: 00000000000706f0
Sep 15 00:07:01 vmgentoo kernel: Call Trace:
Sep 15 00:07:01 vmgentoo kernel:  <TASK>
Sep 15 00:07:01 vmgentoo kernel:  sync_file_release+0x51/0x70
Sep 15 00:07:01 vmgentoo kernel:  __fput+0xdc/0x2a0
Sep 15 00:07:01 vmgentoo kernel:  __x64_sys_close+0x33/0x70
Sep 15 00:07:01 vmgentoo kernel:  do_syscall_64+0x47/0x110
Sep 15 00:07:01 vmgentoo kernel:  entry_SYSCALL_64_after_hwframe+0x76/0x7e
Sep 15 00:07:01 vmgentoo kernel: RIP: 0033:0x7f3adcac6722
Sep 15 00:07:01 vmgentoo kernel: Code: 08 0f 85 a1 4a ff ff 49 89 fb 48 89 f0 48 89 d7 48 89 ce 4c 89 c2 4d 89 ca 4c 8b 44 24 08 4c 8b 4c 24 10 4c 89 5c 24 08 0f 05 <c3> 66 2e 0f 1f 84 00 00 00 00 00 66 2e 0f 1f 84 00 00 00 00 00 66
Sep 15 00:07:01 vmgentoo kernel: RSP: 002b:00007ffd0c5fc908 EFLAGS: 00000246 ORIG_RAX: 0000000000000003
Sep 15 00:07:01 vmgentoo kernel: RAX: ffffffffffffffda RBX: 00007f3ad83b2980 RCX: 00007f3adcac6722
Sep 15 00:07:01 vmgentoo kernel: RDX: 0000000000000000 RSI: 0000000000000000 RDI: 00000000000000cd
Sep 15 00:07:01 vmgentoo kernel: RBP: 000055ce4d6d76f8 R08: 0000000000000000 R09: 0000000000000000
Sep 15 00:07:01 vmgentoo kernel: R10: 0000000000000000 R11: 0000000000000246 R12: 000055ce4cc9b3e0
Sep 15 00:07:01 vmgentoo kernel: R13: 000055ce4ba797b8 R14: 00007ffd0c5fcb00 R15: 00007f3adfe15d70
Sep 15 00:07:01 vmgentoo kernel:  </TASK>
Sep 15 00:07:01 vmgentoo kernel: ---[ end trace 0000000000000000 ]---

```

Going back to 7.2.0 fixed the issue for now.

**Comment by vmlmwiki** [comment]
The problem is caused by 3D acceleration; even with version 7.2.2, it will still throw an error.

**Comment by TommiPrami** [comment]
Seems that not fixed in 7.2.4? 

No time to test now, have to come back into this.

**Comment by AlexanderEichner** [comment]
Thanks for the report, this will hopefully be fixed in the next 7.2.x maintenance release. Would be great if you could try the latest 7.2 testbuild from https://www.virtualbox.org/wiki/Testbuilds .

**Comment by TommiPrami** [comment]
Seems to work OK, thanks...

**Comment by galitsyn-oracle** [comment]
Fix should be available with newly released VirtualBox 7.1.16 and 7.2.6.

**Comment by cmkewish** [comment]
This error is still happening on VirtualBox Graphical User Interface Version 7.2.14 r174565 (Qt6.8.0 on windows 11 host), running a Linux guest OS (AlmaLinux, also happens with Ubuntu guest). It happens relatively frequently, most often when leave VirtualBox running and I unplug my laptop from my office screen at work and then plug it in at home. I'm not sure whether it is a sleep-rewake issue, or a changing desktop resolution issue, or something else. It doesn't happen every time, and I can't see a direct connection between VirtualBox being maximized, minimized, or otherwise, at the time of disconnection.

**Comment by MexMass** [comment]
Version 7.2.14 r174565
Ubuntu guest on Win11 host.

Same issue as @cmkewish - when my screen times out and awakes later i get this issue ~50% of the time.
Its quite annoying as I use my Guest OS as a workspace and some of my work gets lost + have to re-log into all my accounts.
